spring.application.name=BookVerse

#for swagger url customization this is for not UI it is return json only
#springdoc.api-docs.path=/api-docs

#jwt.secretKey=${JWT_SECRET}

#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}